name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: install dependencies
        run: yarn install
      - name: check format
        run: yarn format:check
      - name: contracts
        run: cd packages/contracts && yarn test:ci
      - name: frontend
        run: cd packages/frontend && yarn test:ci
      - name: subgraph
        run: cd packages/subgraph && yarn test:ci
